// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiApp.Context;

#nullable disable

namespace WebApiApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230613104640_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiApp.Context.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "India",
                            ShortName = "IND"
                        },
                        new
                        {
                            Id = 2,
                            Name = "America",
                            ShortName = "AMC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Australia",
                            ShortName = "AUS"
                        });
                });

            modelBuilder.Entity("WebApiApp.Context.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Mumbai",
                            CountryId = 1,
                            Name = "Novotel",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Malegaon",
                            CountryId = 2,
                            Name = "Hira",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Mumbai",
                            CountryId = 1,
                            Name = "Taj",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("WebApiApp.Context.Hotel", b =>
                {
                    b.HasOne("WebApiApp.Context.Country", "country")
                        .WithMany("hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("WebApiApp.Context.Country", b =>
                {
                    b.Navigation("hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
